### ISSUE TITLE
A question on step 6

### ISSUE THREAD

**Issue by YuHuaZeng** [kxgen/facebook-anonymous-publisher#11]
It seems update different paths...
$ cd **/path/to/your/repo/folder**
$ git add .
$ git commit -m 'update publisher settings'
$ git push

**Comment by kxgen** [comment]
Que?

**Comment by YuHuaZeng** [comment]
http://i.imgur.com/YwFxNu9.png

**Comment by kxgen** [comment]
Replace `/path/to/your/repo/folder` to your local folder path.
