### ISSUE TITLE
Greeting, I have some question want to ask you.

### ISSUE THREAD

**Issue by CasparChou** [kxgen/facebook-anonymous-publisher#3]
Sorry, this issue could not be a problem in you code.
I working on this thing too (real time publish to fb page). Due to security issue , I still not open my code . Following two question I have no idea and still happening right now.

Some people will abuse this like just submit "hahaha", how do you resolve this problem ? 
I think that make a blacklist could be work , but it's not easy to be.

Another problem is, some "crazy guy" will use "facebook report service" to report his shit what he submit few time ago. when facebook close those "problem posts", my service will be locked , can't post any post untill I get a new publish token from graph api explorer . BTW, I have multi-board depends on one system, if one of pages "be attacked", and all of my board will be error , have you solved this problem before ?
Also , I found "AnonyMonkey" use their app to retrieve tokens and publish , is it a better way to a real time publish service ?

**Comment by kxgen** [comment]
1. Use regular expression.
2. Detect abusive contents and handle them before Facebook does, or build your own reporting system.
3. Manage different Facebook pages with multiple systems and multiple accounts.
4. With Javascript SDK, you can retrieve your short-lived token and convert it into the long-lived one. With the long-lived token, you can retrieve your page access token (by query /me/accounts),  which will never expire in the future. So maybe you can try to update your page access token every time you log in to your system dashboard.

**Comment by CasparChou** [comment]
Thanks , I will try it this week .
