### ISSUE TITLE
Can't display home page

### ISSUE THREAD

**Issue by jerry9030** [kxgen/facebook-anonymous-publisher#5]
The home page show "Whoops, looks like something went wrong."
But the setting page is correct.
May you tell me how to deal with the problem? thanks.

**Comment by kxgen** [comment]
I am not sure what you mean, could you describe your problem detail?

**Comment by jerry9030** [comment]
Please see the screenshots, thanks!
Homepage:
![homepage](https://cloud.githubusercontent.com/assets/11812189/13598474/e7b23c54-e558-11e5-9221-fd171b1483a6.jpg)
Setting:
![setting](https://cloud.githubusercontent.com/assets/11812189/13598480/ec3a08d8-e558-11e5-85ef-a8ee4db2b7ab.jpg)

**Comment by kxgen** [comment]
Find your `.env` file and change your `APP_DEBUG` value to `true`.

**Comment by jerry9030** [comment]
I have changed .openshift -> .env, but it's still show the error.
![env](https://cloud.githubusercontent.com/assets/11812189/13599430/cf4ec290-e55d-11e5-97d3-e185f0c58e69.jpg)

**Comment by kxgen** [comment]
What's your app environment, local side?

**Comment by jerry9030** [comment]
I use openshift, I try to change the .env, but it's still show the error.

**Comment by kxgen** [comment]
You can not directly change APP_DEBUG on Openshift, click [here](https://github.com/luciddreamz/laravel#development-mode) for more informations.

**Comment by jerry9030** [comment]
Sorry for the delay.
I used the command, but it's still show the error.
Did I do something wrong?
<http://kb-chiahong.rhcloud.com/> (Setting page password used default)
![command](https://cloud.githubusercontent.com/assets/11812189/13728418/c37b2938-e952-11e5-8c56-238b653e7bd0.png)

**Comment by kxgen** [comment]
Try to restart your app from Openshift dashboard.

**Comment by jerry9030** [comment]
I had tried this in the dashboard, but the error still...
I am sorry for any inconvenience this has caused you.

**Comment by jerry9030** [comment]
Thank you for your help, I found that I enter a mistake info in the publisher.php.
I apologize for any inconvenience.

**Comment by kxgen** [comment]
Okay. :)
