### ISSUE TITLE
Word `尛` in image post is broken

### ISSUE THREAD

**Issue by iblis17** [kxgen/facebook-anonymous-publisher#8]
It seems that the font lack of some words like `尛`.

I have a image post contain this word, but it's broke.

**Comment by kxgen** [comment]
Success here: https://www.facebook.com/887450217968295/posts/1037126439667338

**Comment by iblis17** [comment]
Oh... It failed here..
```
└─[iblis@pandapc]% curl curl.kobe.ga/img -d "message=尛測試"
~
~ 　 __ ______　___　____
~ 　/ //_/ __ \/ _ )/ __/
~　/ ,< / /_/ / _　/ _/
~ /_/|_|\____/____/___/_  _____________ 
~   / __/ |/ / ___/  _/ |/ / __/ __/ _ \
~  / _//    / (_ // //    / _// _// , _/
~ /___/_/|_/\___/___/_/|_/___/___/_/|_| 
~                                       
~ ============ PUBLISH SUCCESS ============
~ 
~ [LINK] https://engineer.kobe.ga/3wpBfzE3X
~ 
```

**Comment by kxgen** [comment]
This repo is for the open source publisher version.
The issue you report is the online version for kobeengineer with different core, you can send the message to the Facebook Page admin: https://fb.com/kobeengineer

**Comment by iblis17** [comment]
ok, tnx!
